version: '3.8'

services:
  postgres:
    container_name: whatcook-server-pg
    image: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: whatcook
      POSTGRES_PASSWORD: whatcook
      POSTGRES_DB: whatcook
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

